<template>
  <div>
    <head>
      <title>Search</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" />
    </head>
    <div style="font-family: 'Nunito'; background-color: #f8f9fa; display: flex; flex-direction: column; align-items: center; min-height: 100vh;">
      <div style="margin-top: 40px; text-align: center;">
        <h1 style="font-size: 32px; font-weight: bold; margin-bottom: 20px;">Search for Product</h1>
        <div style="width: 400px; margin: 0 auto;">
          <input v-model="query" type="text" class="form-control" placeholder="Enter your search query" />
        </div>
      </div>

      <div style="width: 90%; display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); grid-gap: 20px; margin-top: 50px;">
        <div v-for="product in filteredProducts" :key="product.id" style="background-color: #fff; box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.1); border-radius: 5px; overflow: hidden; padding: 20px;">
          <img :src="product.image" alt="product card" style="width: 100%; height: 200px; object-fit: cover; margin-bottom: 10px;" />
          <h2 style="font-size: 18px; font-weight: bold; margin-bottom: 10px;">{{ product.name }}</h2>
          <p style="margin-bottom: 5px;">
            <span style="font-weight: bold;">MODEL:</span> {{ product.model }}
          </p>
          <p style="margin-bottom: 5px;">
            <span style="font-weight: bold;">DESCRIPTION:</span> {{ product.description }}
          </p>
          <p style="margin-bottom: 5px;">
            <span style="font-weight: bold;">PRICE:</span> {{ product.price }} DNT
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      query: '',
      products: [],
    };
  },
  async mounted() {
    const { data } = await axios.get('http://localhost:4000/products/products');
    this.products = data;
  },
  computed: {
    filteredProducts() {
      return this.products.filter((product) =>
        product.name.toLowerCase().includes(this.query.toLowerCase())
      );
    },
  },
};
</script>
