<template>
  <div>
    <head>
      <title>ZARA</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      
    </head>
    <navbar/>
<button  @click="handleClick"  style="width: 10em; height: 2.7em; background-color: white; color: black; margin-top: 200px; cursor: pointer; outline: none; border: 1px solid black; font-family: Neue Helvetica, Arial, Helvetica, sans-serif; font-size: 15px;">check users</button>
      <b-carousel id="carousel" controls indicators background="#000" interval="5000">
      <b-carousel-slide caption="Slide 1" img-src="image1.jpg"></b-carousel-slide>
      <b-carousel-slide caption="Slide 2" img-src="image2.jpg"></b-carousel-slide>
      <b-carousel-slide caption="Slide 3" img-src="image3.jpg"></b-carousel-slide>
    </b-carousel>
    <Adminhomemain />
  </div>
</template>

<script>
import navbar from "./navbar.vue";
import Adminhomemain from "../components/AdminhomaeMain.vue";

export default {
  components: {
    navbar,
    Adminhomemain
  },
   methods: {
  handleClick() {
      this.$router.push('/AdminCheck');
    },
   }
};
</script>

<style scoped>
.container {
  padding: 0 0rem;
}

.main {
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.footer {
  display: flex;
  flex: 1;
  padding: 2rem 0;
  border-top: 1px solid #eaeaea;
  justify-content: center;
  align-items: center;
}

.footer a {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-grow: 1;
}

.title a {
  color: #0070f3;
  text-decoration: none;
}

.title a:hover,
.title a:focus,
.title a:active {
  text-decoration: underline;
}

.title {
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
}

.title,
.description {
  text-align: center;
}

.description {
  margin: 4rem 0;
  line-height: 1.5;
  font-size: 1.5rem;
}

.code {
  background: #fafafa;
  border-radius: 5px;
  padding: 0.75rem;
  font-size: 1.1rem;
  font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,
    Bitstream Vera Sans Mono, Courier New, monospace;
}

.grid {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
  max-width: 800px;
}

.card {
  margin: 1rem;
  padding: 1.5rem;
  text-align: left;
  color: inherit;
  text-decoration: none;
  border: 1px solid #eaeaea;
  border-radius: 10px;
  transition: color 0.15s ease, border-color 0.15s ease;
  max-width: 300px;
 
}

.card:hover,
.card:focus,
.card:active {
  color: #0070f3;
  border-color: #0070f3;
}

.card h2 {
  margin: 0 0 1rem 0;
  font-size: 1.5rem;
}


.card p {
  margin: 0;
  font-size: 1.25rem;
  line-height: 1.5;
}

.logo {
  height: 1em;
  margin-left: 0.5rem;
}

@media (max-width: 600px) {
  .grid {
    width: 100%;
    flex-direction: column;
  }
}

@media (prefers-color-scheme: light) {
  .card,
  .footer {
    border-color: #222;
  }
  .code {
    background: rgb(255, 255, 255);
  }
  .logo img {
    filter: invert(1);
    width: 50%;
  }
}

/* Customize navbar styles */
.navbar {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  background: #fff;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  z-index: 100;
}

.navbar-brand {
  margin-left: 1rem;
}

.navbar-nav {
  margin-right: 1rem;
}

.nav-link {
  color: #333;
  margin-left: 1.5rem;
  font-weight: bold;
}

.nav-link:hover,
.nav-link:focus {
  color: #0070f3;
  text-decoration: underline;
}

.carousel-caption {
  color: #fff;
  text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.6);
}

.carousel-indicators {
  bottom: 1rem;
}

.carousel-indicators li {
  background-color: #999;
}

.carousel-indicators li.active {
  background-color: #0070f3;
}

</style>

 
